#!/usr/bin/env sh

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

alias \
  ka="killall" \
  ku="ka -u $USER" \
	yt="yt-dlp ---wait-for-video 60 --add-metadata -i --write-thumbnail" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

alias \
	mv="mv -iv" \
	mkd="mkdir -pv" \
	cp="cp -iv" \
  rm="rm -v" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
  nvim="$EDITOR" \
	sdn="sudo shutdown -h now"

# Abbrev. common command
alias \
  nf="neofetch" \
  gdl="gallery-dl -d $HOME/Pictures/gallery-dl/" \

# Colorize commmand when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -lah --color=auto --group-directories-first" \
	ll="ls -lh --color=auto --group-directories-first" \
	ccat="highlight --out-format=ansi" \
	lsp="pacman -Qett --color=always | less" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# Some other stuffs
alias \
  ref="shortcuts >/dev/null; source ~/.config/shortcutrc"

vf() { fzf | xargs -r -I % $EDITOR % ;}
fh() { eval $(history 1 | fzf +s --tac | sed 's/ *[0-9]* *//') ;}
