#!/bin/sh
bspc rule -r "*"

# Autostart
~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
picom -b &
nitrogen --restore &
dunst &
fcitx5 -d &
sxhkd &	        # Bind keys

###---MONITORS---###
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus true

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

#bspc config borderless_monocle true
#bspc config gapless_monocle true
bspc config single_monocle true

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 0
bspc config window_gap 15

bspc config normal_border_color	  "#1B191A"
bspc config focused_border_color  "#FFDEE7"
bspc config presel_feedback_color "$(xgetres background)"

# bspc config normal_border_color   "#332E57"
# bspc config focused_border_color  "#E5B1A4"

# Remove all rules
bspc rule -r *:*

# 1 > terminal
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a firefox desktop='^2' follow=on focus=on

# 3 > files
declare -a files=(Thunar Pcmanfm Thunar Transmission qBittorrent)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 4 > code
declare -a code=(Geany code-oss)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# 5 > office and docs
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

# 6 > Communication
declare -a comm=(Thunderbird Fluffy-chat discord TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

# 7 > media
declare -a media=(Audacity Music MPlayer Lxmusic Mpv Inkscape Gimp-2.10 obs)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' follow=on focus=on; done

# 8 > settings
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask File-roller Lxrandr Arandr \
System-config-printer.py Pavucontrol Nitrogen Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# special rules
declare -a floating=(alacritty-float Pcmanfm Thunar File-roller \
  Nitrogen Onboard Yad 'Firefox:Places' Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done
