#!/bin/sh
bspc rule -r "*"

# Autostart
~/.config/polybar/launch.sh --pwidgets &
xsetroot -cursor_name left_ptr &
picom -b &
dunst &
uim-xim &
sxhkd &	        # Bind keys
# uim-toolbar-gtk3-systray &

###---MONITORS---###
bspc monitor LVDS-1 -d 一 二 三 四 五

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus true

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

#bspc config borderless_monocle true
#bspc config gapless_monocle true
bspc config single_monocle true

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 0
bspc config window_gap 15

bspc config normal_border_color	  "#1B191A"
bspc config focused_border_color  "#FFDEE7"
bspc config focused_border_color  "#FFDEE7"
bspc config presel_feedback_color "$(xgetres background)"

# bspc config normal_border_color   "#332E57"
# bspc config focused_border_color  "#E5B1A4"
###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Lxappearance state=floating
bspc rule -a Ripcord state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Sxiv state=tiled
