#!/bin/bash

MUSIC_DIR=$HOME/Music

COVER=/tmp/cover.jpg

{
    album="$(mpc --format %album% current)"
    file="$(mpc --format %file% current)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"

    covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER"
    if [[ -n "$src" ]] ; then
        #resize the image's height to 300px & extent it to cover the urxvt length
        convert "$src" -resize 100x "$COVER"
        if [[ -f "$COVER" ]] ; then

                notify-send -i "$COVER" "Now Playing" "$(mpc current)"
                #notify-send -i "$COVER" "Now Playing ♫" "$(mpc current)"
        fi
    fi
} &
